version: "3.9"

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: michel
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - db
    networks:
      - app-network
  db:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./dbdata:/data/db
  webapi:
    container_name: webapi
    deploy:
      mode: replicated
    depends_on:
      - db
    build: ./webapi
    ports:
      - "8000:80"
    networks:
      - app-network
    volumes:
      - ./webapi/src:/var/www/html:rw
#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker volumes
volumes:
  webappsrc:

  dbdata:
