version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network
    volumes:
      - ./mongodata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - app-network
  webapp:
    container_name: webapp
    build: ./webapp
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./webapp/src:/app:rw
  webapi:
    container_name: webapi
    deploy:
      mode: replicated
    build: ./webapi
    ports:
      - "8000:80"
    networks:
      - app-network
    volumes:
      - ./webapi/src:/var/www/html:rw
#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker volumes
volumes:
  webappsrc:
  mongodata:
