version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network
    volumes:
      - ./mongodata:/data/db
    ports:
      - "27017:27017"
  webapp:
    container_name: webapp
    build: ./webapp
    ports:
      - "3000:3000"
      - "4000:4000"
    networks:
      - app-network
    volumes:
      - ./webapp/src:/app:rw
  webapi:
    container_name: webapi
    deploy:
      mode: replicated
    build: ./webapi
    ports:
      - "8000:80"
    networks:
      - app-network
    volumes:
      - ./webapi/src:/var/www/html:rw
#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker volumes
volumes:
  webappsrc:
  mongodata:
