version: "3.9"

services:
  webapp:
      container_name: webapp
      build: ./webapp
      ports:
        - "3000:3000"
      networks:
        - app-network
      volumes:
        - ./webapp/src:/app:rw
#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker volumes
volumes:
  webappsrc:
